# Generated by GPT-5 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="upload_mode",
            field=models.CharField(
                choices=[("FILES", "Files"), ("ARCHIVE", "Archive")],
                default="FILES",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="run_command",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("PY", "Python file"),
                    ("ARCHIVE", "Archive"),
                    ("REQUIREMENTS", "Requirements"),
                    ("OTHER", "Other"),
                ],
                default="PY",
                max_length=20,
            ),
        ),
    ]

