# Generated by Cursor on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_session_upload_mode_and_run_command_and_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysissession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("ANALYZED", "Analyzed"),
                    ("GENERATING_TESTS", "Generating Tests"),
                    ("TESTS_GENERATED", "Tests Generated"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
